# Render Blueprint for Nit-Sys
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: nit-sys
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn nitsys.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: nit-sys-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.4"
    autoDeploy: true
    healthCheckPath: /accounts/login/
    plan: starter

databases:
  - name: nit-sys-db
    databaseName: nitsys
    user: nitsys
    plan: starter
